# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cItfZPVhClnZ4XFNjDNADj2xAY3SXjvM
"""

def Fakultetni_tanlang(guruh):
  if guruh == "614-23":
    return "O'quvchilar soni- 21 ta "
  elif  guruh == "613-23":
    return "o'quvchilar soni-19 ta"
  elif  guruh == "510-23":
    return "O'quvchilar soni-20ta"
  elif  guruh == "680-23":
    return "O'quvchilar soni-18ta"

  else:
    return "Bu guruh fakultetimizda mavjud emas:"
guruh=input("Guruhni kiriting:")
natija=Fakultetni_tanlang(guruh)
print(natija)